/* Generated By:JavaCC: Do not edit this line. CalculatorParserConstants.java */
package org.apfloat.calc;

public interface CalculatorParserConstants {

  int EOF = 0;
  int INTEGER = 3;
  int DECIMAL = 4;
  int DIGIT = 5;
  int IMAGINARY = 6;
  int IDENTIFIER = 7;
  int LETTER = 8;
  int DELIMITER = 9;
  int EOL = 10;
  int INVALID_CHAR = 21;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<INTEGER>",
    "<DECIMAL>",
    "<DIGIT>",
    "<IMAGINARY>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DELIMITER>",
    "<EOL>",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<INVALID_CHAR>",
  };

}
